name: Build costom width JetBrainsMono

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Build costom width JetBrainsMono"
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install python3 fontforge python3-fontforge ttfautohint
          wget "https://github.com/JetBrains/JetBrainsMono/raw/refs/heads/master/fonts/otf/JetBrainsMono-Regular.otf"

      - name: Build
        run: |
          mkdir 500width
          python WidthChanger.py JetBrainsMono-Regular.otf 500width 0.8333
          cd 500width
          mv $(ls) JetBrainsMono-Regular-500Width.otf
          cp HintingChecker.sh .
          cp JetBrainsMono-Regular-500Width.otf Unhinted.otf
          chmod +x HintingChecker.sh
          source HintingChecker.sh Unhinted.otf

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: JetBrainsMono-Regular-500Width
          path: 500width/JetBrainsMono-Regular-500Width.otf

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Unhinted
          path: 500width/Unhinted*

      - name: Check info
        run: |
          ls -ltrah
          ls -ltra
      

      
