name: Build costom width JetBrainsMono

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Build costom width JetBrainsMono"
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install python3 fontforge python3-fontforge ttfautohint
          pip install fonttools
          wget -O Iovevka-Medium.ttf "https://github.com/5hes/Iosevka_fork/releases/download/v0.0.1.8/Iovevka-CondensedMedium-Unhinted.ttf"

      - name: Build
        run: |
          mkdir 600width
          python WidthChanger.py Iovevka-Medium.ttf 600width 1.5
          cd 600width
          mv $(ls) Iovevka-600.ttf
          cp Iovevka-600.ttf origin.ttf
          cp ../HintingChecker.sh .
          cp Iovevka-600.ttf Unhinted.ttf
          ttx -o temp.ttx Unhinted.ttf
          chmod +x HintingChecker.sh
          source HintingChecker.sh Unhinted.ttf

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Iovevka-Medium-600Width
          path: 600width/Ioseveka-600.ttf

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Unhinted
          path: 600width/Unhinted*

      - name: Check info
        run: |
          tree
          cd 500width
          ls -ltrah
          ls -ltra
      

      
